### ISSUE TITLE
无法进行搜索

### ISSUE THREAD

**Issue by EdwinWang0508** [huamang/SiYuan-Search-workflow#2]
输入sy关键词后没反应，python和requests库都是装了的
下面是log具体信息
谢谢作者
```
[21:53:57.897] SiYuan[Script Filter] Queuing argument '(null)'
[21:53:58.045] SiYuan[Script Filter] Script with argv '(null)' finished
[21:53:58.051] ERROR: SiYuan[Script Filter] Code 1: Traceback (most recent call last):
  File "/Users/edwinwang/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C45DBC4D-F381-4591-ADFC-EC5486E23233/search.py", line 57, in <module>
    main()
  File "/Users/edwinwang/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C45DBC4D-F381-4591-ADFC-EC5486E23233/search.py", line 53, in main
    parseRes(resJson)
  File "/Users/edwinwang/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C45DBC4D-F381-4591-ADFC-EC5486E23233/search.py", line 37, in parseRes
    for block in resJson ["data"]["blocks"]:
KeyError: 'data'
[21:53:58.270] SiYuan[Script Filter] Queuing argument '(null)'
[21:53:58.418] SiYuan[Script Filter] Script with argv '(null)' finished
[21:53:58.423] ERROR: SiYuan[Script Filter] Code 1: Traceback (most recent call last):
  File "/Users/edwinwang/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C45DBC4D-F381-4591-ADFC-EC5486E23233/search.py", line 57, in <module>
    main()
  File "/Users/edwinwang/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C45DBC4D-F381-4591-ADFC-EC5486E23233/search.py", line 53, in main
    parseRes(resJson)
  File "/Users/edwinwang/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C45DBC4D-F381-4591-ADFC-EC5486E23233/search.py", line 37, in parseRes
    for block in resJson ["data"]["blocks"]:
KeyError: 'data'
```

**Comment by huamang** [comment]
请查看下自己的思源是不是开了web服务，或者端口有没有配置正确，这里报错看起来是请求的返回内容为空

**Comment by EdwinWang0508** [comment]
web服务是指网络伺服吗，我一直没有开启过，端口的话现在是固定6806，workflow里我也不知道如何修改，我使用的是思源2.9.1
我重装了思源和workflow，似乎还是一样的错误
```
[15:32:42.410] SiYuan[Script Filter] Queuing argument 'sep'
[15:32:42.504] SiYuan[Script Filter] Script with argv '(null)' finished
[15:32:42.509] ERROR: SiYuan[Script Filter] Code 1: Traceback (most recent call last):
  File "/Users/edwinwang/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A73C9D10-C775-4B59-9699-E72DE2DBFE81/search.py", line 57, in <module>
    main()
  File "/Users/edwinwang/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A73C9D10-C775-4B59-9699-E72DE2DBFE81/search.py", line 53, in main
    parseRes(resJson)
  File "/Users/edwinwang/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A73C9D10-C775-4B59-9699-E72DE2DBFE81/search.py", line 37, in parseRes
    for block in resJson["data"]["blocks"]:
KeyError: 'data'
```

**Comment by huamang** [comment]
抱歉这段时间比较忙没有回复你；有可能是版本更新后搜索返回字段改变了，你可以试试2.8.x版本，我正在使用的是2.8.6使用正常，后面的版本我会在端午后尝试更新脚本

**Comment by huamang** [comment]
刚刚我尝试更新了2.9.1版本，发现是能正常使用的，你可以单独跑一下python脚本，看看是否能正常运行，这里我设置的命令是python3 search.py "{query}"，有可能你本地环境得改一改，比如python search.py "{query}"

**Comment by EdwinWang0508** [comment]
> python search.py "{query}"

之前就试过了，提示command not found 
看来只能在思源内搜索了😂

**Comment by EdwinWang0508** [comment]
[
<img width="650" alt="图片" src="https://github.com/huamang/SiYuan-Search-workflow/assets/64629689/a88b42d9-6d49-4099-8a54-265896c7a953">
](url)
突然发现报错`No module named 'requests'`
但是库里面是有的

**Comment by huamang** [comment]
哈哈哈那真奇怪了，可能是你有多个版本的python3，而这个pip3安装的库不是你正在使用的Python3
